<script lang="ts">
	import ArticleLayout from '$lib/components/ArticleLayout.svelte';

	const metadata = {
		title: "Giving AI Agents Robust Image Generation Capabilities",
		date: "October 20, 2025",
		categories: ["MCP", "Image Generation", "FLUX", "Developer Tools", "AI"],
		slug: "giving-ai-agents-robust-image-generation-capabilities",
		description: "Built an MCP server that brings FLUX image generation directly into Claude Code. Generate blog images, UI mockups, and design variations without leaving your coding environment.",
		image: "https://kmaurinjones.dev/images/thoughts/giving-ai-agents-robust-image-generation-capabilities/hero.webp",
		mediumUrl: ""
	};
</script>

<ArticleLayout
	title={metadata.title}
	date={metadata.date}
	categories={metadata.categories}
	slug={metadata.slug}
	description={metadata.description}
	image={metadata.image}
>
	<!-- Hero Image -->
	<figure class="my-8">
		<img src="/images/thoughts/giving-ai-agents-robust-image-generation-capabilities/hero.webp"
			 alt="Abstract digital illustration of AI neural networks transforming into vibrant images"
			 class="w-[70%] md:w-[60%] lg:w-[50%] mx-auto" />
		<figcaption class="text-center text-sm text-taupe mt-2">
			Image by author. Generated using FLUX1.1 Pro Ultra via the Flux MCP during article creation.
		</figcaption>
	</figure>

	<p>Text-based AI agents like Claude Code are incredibly powerful for software development, but they hit a wall when visual content is needed. Need a hero image for your blog post? Generate UI mockups? Create variations of a design? You're forced to context-switch to a separate tool, breaking flow and adding friction.</p>

	<p>I built a solution in 20 minutes: an MCP (Model Context Protocol) server that brings FLUX image generation directly into Claude Code and other MCP clients.</p>

	<h2>The Problem with Text-Only Agents</h2>

	<p>Claude Code excels at writing code, refactoring, debugging, and system administration. But it's text-dominant by nature. When I'm writing technical articles or building interfaces, I constantly need visual assets. The workflow looked like this:</p>

	<ol>
		<li>Work in Claude Code</li>
		<li>Switch to Replicate/ChatGPT/Midjourney for images</li>
		<li>Download files manually</li>
		<li>Move them to the right directory</li>
		<li>Return to Claude Code</li>
	</ol>

	<p>Each context switch costs time and mental energy. I wanted to multimodalize the agent—give it native image generation capabilities without leaving the terminal.</p>

	<h2>Building the FLUX MCP</h2>

	<p>The Model Context Protocol makes this straightforward. An MCP server exposes tools that AI agents can call directly. I built a Node.js server that wraps Replicate's FLUX API, exposing two tools:</p>

	<ul>
		<li><code>flux_models</code> — Lists all 6 available FLUX models with usage notes</li>
		<li><code>flux_generate</code> — Generates images with full control over model, aspect ratio, output format, resolution, and advanced parameters</li>
	</ul>

	<p>The implementation took about 20 minutes with Claude Code handling most of the heavy lifting. The server validates paths (preventing directory traversal attacks), enforces HTTPS-only URLs, and restricts downloads to Replicate's CDN for security.</p>

	<p>Installation is simple:</p>

	<pre><code class="language-bash">claude mcp add flux-mcp \
  --env REPLICATE_API_TOKEN=r8_your_token \
  -- node /path/to/flux-mcp/index.js</code></pre>

	<p>For Claude Desktop users:</p>

	<pre><code class="language-json">{`{
  "mcpServers": {
    "flux-mcp": {
      "command": "node",
      "args": ["/absolute/path/to/flux-mcp/index.js"],
      "env": {
        "REPLICATE_API_TOKEN": "r8_your_token"
      }
    }
  }
}`}</code></pre>

	<h2>Using It (Meta!)</h2>

	<p>I'm using the Flux MCP right now to write this article. The hero image you see above was generated by Claude Code calling <code>flux_generate</code> with FLUX1.1 Pro Ultra, 16:9 aspect ratio, raw realism mode enabled, and PNG output format. The agent saved it directly to the article's image directory without me touching a file browser.</p>

	<figure class="my-8">
		<img src="/images/thoughts/giving-ai-agents-robust-image-generation-capabilities/claude-code-usage-screenshot.png"
			 alt="Screenshot of Claude Code using the Flux MCP to generate images during article creation"
			 class="w-[70%] md:w-[60%] lg:w-[50%] mx-auto" />
		<figcaption class="text-center text-sm text-taupe mt-2">
			Live screenshot of Claude Code using the Flux MCP during this article's creation.
		</figcaption>
	</figure>

	<p>The workflow is frictionless: I describe what I need, the agent generates it, and we keep moving. No context switching. No manual file management.</p>

	<h3>Example Generations</h3>

	<p>Here are a few examples generated while writing this article, demonstrating different use cases:</p>

	<figure class="my-8">
		<img src="/images/thoughts/giving-ai-agents-robust-image-generation-capabilities/ui-mockup-example.webp"
			 alt="Modern task management dashboard UI mockup with cream background and navy blue accents"
			 class="w-[70%] md:w-[60%] lg:w-[50%] mx-auto" />
		<figcaption class="text-center text-sm text-taupe mt-2">
			UI mockup generated with FLUX Pro (16:9, WebP). Prompt: "Clean minimal UI mockup of a modern task management dashboard, soft cream background, navy blue headers, terracotta accent buttons."
		</figcaption>
	</figure>

	<figure class="my-8">
		<img src="/images/thoughts/giving-ai-agents-robust-image-generation-capabilities/technical-diagram-example.webp"
			 alt="Abstract technical diagram showing network nodes and data flow"
			 class="w-[70%] md:w-[60%] lg:w-[50%] mx-auto" />
		<figcaption class="text-center text-sm text-taupe mt-2">
			Technical illustration generated with FLUX Pro (3:2, WebP). Prompt: "Abstract technical illustration of connected network nodes and data flow, geometric shapes, modern clean design."
		</figcaption>
	</figure>

	<p>Each took seconds to generate and was saved directly to the article's image directory—no manual downloads, no switching contexts.</p>

	<h2>Why It Matters</h2>

	<p>The models are older than cutting-edge options like Gemini's latest image generators, so quality may not match the newest tools. But for abstract content, UI mockups, and technical illustrations, FLUX performs extremely well.</p>

	<p>The real win is UX. Keeping image generation inside the agent's workflow reduces friction dramatically. When building projects that blend code and visuals—landing pages, technical articles, design systems—the Flux MCP makes the entire process feel cohesive.</p>

	<p>The core concept is entirely modular. Though I've used the FLUX model family via Replicate here, it's straightforward to fork this MCP and swap in different models for different purposes. Want to use GPT-Image for technical diagrams, Google's Nano Banana for photorealism, and Midjourney for artistic content? Build your own fleet of image generation and editing models, all accessible through a single MCP interface. The same pattern could extend to video generation once APIs become more broadly available.</p>

	<p>This is what multimodal agents should feel like: text, code, and images handled seamlessly within a single interface.</p>

	<h2>Links</h2>
	<ul>
		<li><strong>GitHub Repository</strong>: <a href="https://github.com/kmaurinjones/flux-mcp" target="_blank" rel="noopener">flux-mcp</a></li>
		<li><strong>LinkedIn</strong>: <a href="https://www.linkedin.com/in/kmaurinjones/" target="_blank" rel="noopener">linkedin.com/in/kmaurinjones</a></li>
		<li><strong>Email</strong>: <a href="mailto:kmaurinjones@gmail.com">kmaurinjones@gmail.com</a></li>
	</ul>
</ArticleLayout>
